version: "3.8"

services:
  db:
    image: mysql:8.2
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?error}
      MYSQL_USER: ${MYSQL_USER:?error}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?error}
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3

  wp:
    image: wordpress:6.4
    depends_on:
      - db
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:?error}
      WORDPRESS_DB_USER: ${MYSQL_USER:?error}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:?error}

volumes:
  db:
