services:
  db:
    image: mariadb:11.2.2
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?error}
      MARIADB_DATABASE: ${DB_DATABASE:?error}
      MARIADB_USER: ${DB_USER:?error}
      MARIADB_PASSWORD: ${DB_PASSWORD:?error}
    networks:
      - wp

  wp:
    build: .
    depends_on:
      - db
    volumes:
      - wp:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_DATABASE:?error}
      WORDPRESS_DB_USER: ${DB_USER:?error}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:?error}
    networks:
      - wp

  nginx:
    image: nginx:1.25.3-alpine
    depends_on:
      - wp
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - wp:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d:ro
    networks:
      - wp

volumes:
  db:
  wp:

networks:
  wp:
    driver: bridge
