services:
  db:
    image: mariadb:11.2.2
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?error}
      MARIADB_DATABASE: ${DB_DATABASE:?error}
      MARIADB_USER: ${DB_USER:?error}
      MARIADB_PASSWORD: ${DB_PASSWORD:?error}
    networks:
      - wp

  wp:
    image: wordpress:6.4
    depends_on:
      - db
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_DATABASE:?error}
      WORDPRESS_DB_USER: ${DB_USER:?error}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:?error}
    networks:
      - wp

volumes:
  db:

networks:
  wp:
    driver: bridge
