name: Deploy WP

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: wp
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-deps
