name: Deploy WP

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: wp
    steps:
      - name: Checkout
        uses: actions/checkout@v3
